printWidth: 80
singleQuote: true
jsxSingleQuote: true
arrowParens: always
overrides:
  - files: "*.sol"
    options:
        bracketSpacing: false
        printWidth: 80
        singleQuote: false
        tabWidth: 4
        useTabs: false
        explicitTypes: "always"
